CREATE DATABASE db_QuanLyHeThongNhaThuocLongChau

USE db_QuanLyHeThongNhaThuocLongChau

CREATE TABLE tbl_LoaiSanPham
(
	PK_sMaLoai VARCHAR(10) NOT NULL CONSTRAINT PK_sMaLoai PRIMARY KEY,
	sTenLoai NVARCHAR(100) NOT NULL
);

CREATE TABLE tbl_SanPham
(
	PK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT PK_SanPham PRIMARY KEY,
	sTenSP NVARCHAR(100) NOT NULL,
	sDonViTinh NVARCHAR(10) NOT NULL,
	sHanDung NVARCHAR(10) NOT NULL,
	iSL INT DEFAULT 0 NOT NULL,
	fDonGiaBan FLOAT NOT NULL,
	FK_sMaLoai VARCHAR(10) NOT NULL CONSTRAINT FK_SanPham_LoaiSanPham FOREIGN KEY REFERENCES dbo.tbl_LoaiSanPham(PK_sMaLoai)
);

CREATE TABLE tbl_NhaCungCap
(
	PK_sMaNCC VARCHAR(10) NOT NULL CONSTRAINT PK_NhaCungCap PRIMARY KEY,
	sTenNCC NVARCHAR(100) NOT NULL,
	sDiaChi NVARCHAR(100) NULL,
	sSDT VARCHAR(10) NOT NULL,
	sSoTK VARCHAR(20) NULL
);

CREATE TABLE tbl_KhachHang
(
	PK_sMaKH VARCHAR(10) NOT NULL CONSTRAINT PK_KhachHang PRIMARY KEY,
	sTenKH NVARCHAR(50) NOT NULL,
	sSDT VARCHAR(10) NOT NULL
);

CREATE TABLE tbl_Quyen
(
	PK_sMaQuyen VARCHAR(10) NOT NULL CONSTRAINT PK_Quyen PRIMARY KEY,
	sTenQuyen NVARCHAR(20) NOT NULL
);

CREATE TABLE tbl_TaiKhoan
(
	PK_sMaTK VARCHAR(10) NOT NULL CONSTRAINT PK_TaiKhoan PRIMARY KEY,
	sTenTK VARCHAR(20) NOT NULL,
	sMK VARCHAR(20) NOT NULL,
	FK_sMaQuyen VARCHAR(10) NOT NULL CONSTRAINT FK_TaiKhoan_Quyen FOREIGN KEY REFERENCES dbo.tbl_Quyen(PK_sMaQuyen)
);

CREATE TABLE tbl_NhanVien
(
	PK_sMaNV VARCHAR(10) NOT NULL CONSTRAINT PK_NhanVien PRIMARY KEY,
	FK_sMaTK VARCHAR(10) NOT NULL CONSTRAINT FK_NhanVien_TaiKhoan FOREIGN KEY REFERENCES dbo.tbl_TaiKhoan(PK_sMaTK),
	sHoTen NVARCHAR(50) NOT NULL,
	dNgaySinh DATETIME NOT NULL,
	sCCCD VARCHAR(12) NOT NULL,
	sSDT VARCHAR(10) NOT NULL,
	dNgayVaoLam DATETIME NOT NULL,
	sCVu NVARCHAR(20) NOT NULL
);

CREATE TABLE tbl_PhieuYeuCau
(
	PK_sMaPYC VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuYeuCau PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuYeuCau_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV)
);

CREATE TABLE tbl_CTPhieuYeuCau
(
	PK_FK_sMaPYC VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuYeuCau_PhieuYeuCau FOREIGN KEY REFERENCES dbo.tbl_PhieuYeuCau(PK_sMaPYC),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuYeuCau_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSLCan INT DEFAULT 1 NOT NULL,
	iSLDuyet INT NOT NULL,
	CONSTRAINT PK_CTPhieuYeuCau PRIMARY KEY (PK_FK_sMaPYC, PK_FK_sMaSP)
);

CREATE TABLE tbl_PhieuDatHang
(
	PK_sMaPDH VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuDatHang PRIMARY KEY,
	FK_sMaPYC VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuDatHang_PhieuYeuCau FOREIGN KEY REFERENCES dbo.tbl_PhieuYeuCau(PK_sMaPYC),
	dTgLap DATETIME NOT NULL,
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuDatHang_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV)
);

CREATE TABLE tbl_CTPhieuDatHang
(
	PK_FK_sMaPDH VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuDatHang_PhieuDatHang FOREIGN KEY REFERENCES dbo.tbl_PhieuDatHang(PK_sMaPDH),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuDatHang_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT DEFAULT 1 NOT NULL,
	CONSTRAINT PK_CTPhieuDatHang PRIMARY KEY (PK_FK_sMaPDH, PK_FK_sMaSP)
);

CREATE TABLE tbl_PhieuGiaoHang
(
	PK_sMaPGH VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuGiaoHang PRIMARY KEY,
	FK_sMaPDH VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuGiaoHang_PhieuDatHang FOREIGN KEY REFERENCES dbo.tbl_PhieuDatHang(PK_sMaPDH),
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuGiaoHang_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	sHoTenGH NVARCHAR(50) NOT NULL,
	sSDTGH VARCHAR(10) NOT NULL
);

CREATE TABLE tbl_CTPhieuGiao
(
	PK_FK_sMaPGH VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuGiao_PhieuGiaoHang FOREIGN KEY REFERENCES dbo.tbl_PhieuGiaoHang(PK_sMaPGH),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuGiao_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT NOT NULL,
	CONSTRAINT PK_CTPhieuGiao PRIMARY KEY (PK_FK_sMaPGH, PK_FK_sMaSP)
);

CREATE TABLE tbl_PhieuNhapKho
(
	PK_sMaPN VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuNhapKho PRIMARY KEY,
	FK_sMaPGH VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuNhapKho_PhieuGiaoHang FOREIGN KEY REFERENCES dbo.tbl_PhieuGiaoHang(PK_sMaPGH),
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuNhapKho_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV)
);

CREATE TABLE tbl_CTPhieuNhapKho
(
	PK_FK_sMaPN VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuNhapKho_PhieuNhapKho FOREIGN KEY REFERENCES dbo.tbl_PhieuNhapKho(PK_sMaPN),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuNhapKho_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT DEFAULT 1 NOT NULL,
	sGhiChu NVARCHAR(100) NULL,
	CONSTRAINT PK_CTPhieuNhapKho PRIMARY KEY (PK_FK_sMaPN, PK_FK_sMaSP)
);

CREATE TABLE tbl_HopDongCungCap
(
	PK_sMaHD VARCHAR(10) NOT NULL CONSTRAINT PK_HopDongCungCap PRIMARY KEY,
	FK_sMaNCC VARCHAR(10) NOT NULL CONSTRAINT FK_HopDongCungCap_NhaCungCap FOREIGN KEY REFERENCES dbo.tbl_NhaCungCap(PK_sMaNCC),
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_HopDongCungCap_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	dNgayBatDau DATETIME NOT NULL,
	dNgayketThuc DATETIME NOT NULL
);

CREATE TABLE tbl_CTHopDongCungCap
(
	PK_FK_sMaHD VARCHAR(10) NOT NULL CONSTRAINT FK_CTHopDongCungCap_HopDongCungCap FOREIGN KEY REFERENCES dbo.tbl_HopDongCungCap(PK_sMaHD),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTHopDongCungCap_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	fDonGia FLOAT NOT NULL,
	CONSTRAINT PK_CTHopDongCungCap PRIMARY KEY(PK_FK_sMaHD, PK_FK_sMaSP)
);

CREATE TABLE tbl_PhieuChi
(
	PK_sMaPChi VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuChi PRIMARY KEY,
	FK_sMaPN VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuChi_PhieuNhap FOREIGN KEY REFERENCES dbo.tbl_PhieuNhapKho(PK_sMaPN),
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuChi_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	sHinhThucTT NVARCHAR(20) NOT NULL
);

CREATE TABLE tbl_CTPhieuChi
(
	PK_FK_sMaPChi VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuChi_PhieuChi FOREIGN KEY REFERENCES dbo.tbl_PhieuChi(PK_sMaPChi),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuChi_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	CONSTRAINT PK_CTPhieuChi PRIMARY KEY(PK_FK_sMaPChi, PK_FK_sMaSP)
);

CREATE TABLE tbl_PhieuXuatKho
(
	PK_sMaPX VARCHAR(10) NOT NULL CONSTRAINT PK_PhieuXuatKho PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuXuatKho_NhanVienLap FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	FK_sMaNguoiLay VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuXuatKho_NhanVienLay FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV)
);

CREATE TABLE tbl_CTPhieuXuatKho
(
	PK_FK_sMaPX VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuXuatKho_PhieuXuatKho FOREIGN KEY REFERENCES dbo.tbl_PhieuXuatKho(PK_sMaPX),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuXuatKho_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSLYC INT NOT NULL,
	iSLX INT NOT NULL,
	sGhiChu NVARCHAR(100) NULL
);

CREATE TABLE tbl_PhieuThu
(
	PK_sMaPT VARCHAR(10) CONSTRAINT PK_PhieuThu PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuThu_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	FK_sMaKH VARCHAR(10) NOT NULL CONSTRAINT FK_PhieuThu_KhachHang FOREIGN KEY REFERENCES dbo.tbl_KhachHang(PK_sMaKH),
	sHinhThucTT NVARCHAR(20) NOT NULL
);

CREATE TABLE tbl_CTPhieuThu
(
	PK_FK_sMaPT VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuThu_PhieuThu FOREIGN KEY REFERENCES dbo.tbl_PhieuThu(PK_sMaPT),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTPhieuThu_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT NOT NULL DEFAULT 1,
	CONSTRAINT PK_CTPhieuThu PRIMARY KEY (PK_FK_sMaPT, PK_FK_sMaSP)
);

CREATE TABLE tbl_BienBanHuy
(
	PK_sMaBBH VARCHAR(10) NOT NULL CONSTRAINT PK_BienBanHuy PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_BienBanHuy_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	sDiaDiemHuy NVARCHAR(100) NOT NULL,
	dTgBatDau DATETIME NOT NULL,
	dTgKetThuc DATETIME NOT NULL,
	sPhuongThucHuy NVARCHAR(20) NOT NULL
);

CREATE TABLE tbl_CTBienBanHuy
(
	PK_FK_sMaBBH VARCHAR(10) NOT NULL CONSTRAINT FK_CTBienBanHuy_BienBanHuy FOREIGN KEY REFERENCES dbo.tbl_BienBanHuy(PK_sMaBBH),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTBienBanHuy_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT NOT NULL DEFAULT 1,
	sLyDo NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_CTBienBanHuy PRIMARY KEY (PK_FK_sMaBBH, PK_FK_sMaSP)
);

CREATE TABLE tbl_ThanhVienHuy
(
	PK_FK_MaBBH VARCHAR(10) NOT NULL CONSTRAINT FK_ThanhVienHuy_BienBanHuy FOREIGN KEY REFERENCES dbo.tbl_BienBanHuy(PK_sMaBBH),
	PK_FK_sMaNguoiHuy VARCHAR(10) NOT NULL CONSTRAINT FK_ThanhVienHuy_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	CONSTRAINT PK_ThanhVienHuy PRIMARY KEY (PK_FK_MaBBH, PK_FK_sMaNguoiHuy)
);

CREATE TABLE tbl_BienBanKiemKe
(
	PK_sMaBBK VARCHAR(10) NOT NULL CONSTRAINT PK_BienBanKiemKe PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_BienBanKiemKe_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	sDiaDiemKiem NVARCHAR(100) NOT NULL,
	dTgBatDau DATETIME NOT NULL,
	dTgKetThuc DATETIME NOT NULL
);

CREATE TABLE tbl_CTBienBanKiemKe
(
	PK_FK_sMaBBK VARCHAR(10) NOT NULL CONSTRAINT FK_CTBienBanKiemKe_BienBanKiemKe FOREIGN KEY REFERENCES dbo.tbl_BienBanKiemKe(PK_sMaBBK),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTBienBanKiemKe_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	iSL INT NOT NULL,
	CONSTRAINT PK_CTBienBanKiemKe PRIMARY KEY (PK_FK_sMaBBK, PK_FK_sMaSP)
);

CREATE TABLE tbl_ThanhVienKiemKe
(
	PK_FK_sMaBBK VARCHAR(10) NOT NULL CONSTRAINT FK_ThanhVienKiemKe_BienBanKiemKe FOREIGN KEY REFERENCES dbo.tbl_BienBanKiemKe(PK_sMaBBK),
	PK_FK_sMaNguoiKiem VARCHAR(10) NOT NULL CONSTRAINT FK_ThanhVienKiemKe_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	CONSTRAINT PK_ThanhVienKiemKe PRIMARY KEY (PK_FK_sMaBBK, PK_FK_sMaNguoiKiem)
);