CREATE TABLE tbl_BaoCaoThuChi
(
	PK_sMaBC VARCHAR(10) NOT NULL CONSTRAINT PK_BaoCaoThuChi PRIMARY KEY,
	dTgLap DATETIME NOT NULL DEFAULT GETDATE(),
	FK_sMaNguoiLap VARCHAR(10) NOT NULL CONSTRAINT FK_BaoCaoThuChi_NhanVien FOREIGN KEY REFERENCES dbo.tbl_NhanVien(PK_sMaNV),
	dTgBatDau DATETIME NOT NULL,
	dTgKetThuc DATETIME NOT NULL,
	bTrangThai BIT NOT NULL
)

CREATE TABLE tbl_CTBaoCaoThuChi
(
	PK_FK_sMaBC VARCHAR(10) NOT NULL CONSTRAINT FK_CTBaoCaoThuChi_BaoCaoThuChi FOREIGN KEY REFERENCES dbo.tbl_BaoCaoThuChi(PK_sMaBC),
	PK_FK_sMaSP VARCHAR(10) NOT NULL CONSTRAINT FK_CTBaoCaoThuChi_SanPham FOREIGN KEY REFERENCES dbo.tbl_SanPham(PK_sMaSP),
	CONSTRAINT PK_CTBaoCaoThuChi PRIMARY KEY (PK_FK_sMaBC, PK_FK_sMaSP)
)